actin-filaments: 0
plasma-membrane: 1
centrosome: 2
cytosol: 3
endoplasmic-reticulum: 4
endosomes: 5
golgi-apparatus: 6
intermediate-filaments: 7
lipid-droplets: 8
lysosomes: 9
microtubules: 10
mitochondria: 11
nuclear-bodies: 12
nuclear-membrane: 13
nuclear-speckles: 14
nucleoli: 15
nucleoli-fibrillar-center: 16
nucleoplasm: 17
peroxisomes: 18
vesicles: 19